### ISSUE TITLE
Leaxer Kavgası

### ISSUE THREAD

**Issue by uzaybl01** [Constani/superapi#1]
Sıpanç `" Constaniyi bitirip leaxer'ı göt etmezsem en büyük orospu evladıyım "` böyle bir söz söylemişti
Sizce kaç ayda biter ?

- Qumala Savesta
- - Nalax | rel0aded_v2

**Comment by benerenla** [comment]
bunun olayı ne şimdi

**Comment by SpongeBed81** [comment]
bu issue ne abi

**Comment by Tastyy1** [comment]
bence temiz bi 2 ayı var

**Comment by ileaxer** [comment]
Yani bu kesinlikle Developer ekibine bağlı onlar ne kadar sıklıkla çalışırsa erken biter ama ne kadar yarım yarım devam ederlerse 2 ay ve daha fazlası olacağı aşikar.
